# Generated by Django 5.1.1 on 2024-10-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=12)),
                ('nom', models.CharField(max_length=50)),
                ('prenoms', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('adresse', models.CharField(max_length=50)),
                ('histoMedic', models.CharField(max_length=255)),
            ],
        ),
    ]
