# Generated by Django 5.1.1 on 2024-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='histoMedic',
            field=models.TextField(),
        ),
    ]
