# Generated by Django 5.1.1 on 2024-10-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
