# Generated by Django 5.1.1 on 2024-10-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
