# Generated by Django 5.1.1 on 2024-10-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_doctor_age_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
