# Generated by Django 5.1.1 on 2024-10-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grade'),
        ),
    ]
