# Generated by Django 5.1.1 on 2024-10-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_doctor_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speciality/'),
        ),
    ]
