# Generated by Django 5.1.1 on 2024-10-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_speciality_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='prenoms',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='nom',
            new_name='name',
        ),
    ]
