# Generated by Django 5.1.1 on 2024-10-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_prenoms_doctor_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='prenoms',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
    ]
