# Generated by Django 5.1.1 on 2024-10-30 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_prenoms_patient_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
