# Generated by Django 5.1.1 on 2024-10-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
        ),
    ]
