# Generated by Django 5.1.1 on 2024-10-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_patient_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Non spécifié', max_length=30),
        ),
    ]
