# Generated by Django 5.1.1 on 2024-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adresse',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='histoMedic',
            field=models.TextField(default=''),
        ),
    ]
