# Generated by Django 5.1.1 on 2024-11-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_patient_adresse_alter_patient_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(default='00:30:00'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmé', 'Confirmé'), ('annulé', 'Annulé'), ('en attente', 'En attente')], default='en attente', max_length=20),
        ),
    ]
